name: gcc on linux test suite

on:
  push:
   branches:
     - master

jobs:
  test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: install gcc-11
          run: sudo apt install g++-11
        - name: test
          run: |
            echo 'testing'
            cd tests/
            bash create_cmake_dir
            cd cmake-build-default
            cmake -D CMAKE_CXX_COMPILER=g++-11 ..
            cmake --build .
            ./flippy_test
            echo "done testing"
